name: Deploy to github pages
on:
  workflow_dispatch:
# By default, jobs run in parallel. To run them sequentially, you can use the `needs` keyword.
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs

      - name: Run tests
        run: npm test

  Build:
    # This job depends on the Test job. It will only run if the Test job is successful.
    # E.g. needs: Test or needs: [Test, AnotherJob]
    needs: Test # "Test" is the job name
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs
        with:
          node-version: "20"

      - name: Build project
        run: npm run build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist

  Deploy:
    runs-on: ubuntu-latest
    needs: Build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
