name: Deploy
on:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
