name: Deploy
on:
  workflow_dispatch:
# By default, jobs run in parallel. To run them sequentially, you can use the `needs` keyword.
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs

      - name: Run tests
        run: npm test

  Build:
    # This job depends on the Test job. It will only run if the Test job is successful.
    # E.g. needs: Test or needs: [Test, AnotherJob]
    needs: Test # "Test" is the job name
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Install Dependencies
        uses: ./.github/actions/setup-nodejs

      - name: Build project
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  Deploy:
    runs-on: ubuntu-latest
    needs: Build # "Build" is the job name
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist

      - name: Deploy Artifacts
        run: |
          ls dist
          echo "Deploying artifacts..."
